import { PrismaClient } from "../src/generated/prisma/client.js";

const prisma = new PrismaClient();

const products = [
  // ---------- TAILLIGHT ----------
  {
    name: "Honda Civic Clear Tail Light - Right",
    slug: "honda-civic-clear-taillight-right-2006-2008",
    description: "OEM-style clear lens tail light, passenger side.",
    sku: "TL-CIV-06-08-R",
    category: "TAILLIGHT",
    priceCents: 8999,
    stock: 10,
    make: "Honda",
    model: "Civic",
    yearFrom: 2006,
    yearTo: 2008,
    color: "Clear",
    side: "Right",
  },
  {
    name: "BMW E46 Clear Tail Light - Left",
    slug: "bmw-e46-clear-taillight-left-1999-2001",
    description: "Clear lens tail light replacement for BMW E46.",
    sku: "TL-E46-99-01-L",
    category: "TAILLIGHT",
    priceCents: 11999,
    stock: 8,
    make: "BMW",
    model: "3 Series E46",
    yearFrom: 1999,
    yearTo: 2001,
    color: "Clear",
    side: "Left",
  },
  {
    name: "BMW E46 Clear Tail Light - Right",
    slug: "bmw-e46-clear-taillight-right-1999-2001",
    description: "Clear lens tail light replacement for BMW E46.",
    sku: "TL-E46-99-01-R",
    category: "TAILLIGHT",
    priceCents: 11999,
    stock: 7,
    make: "BMW",
    model: "3 Series E46",
    yearFrom: 1999,
    yearTo: 2001,
    color: "Clear",
    side: "Right",
  },
  {
    name: "Toyota Camry LED Tail Light - Left",
    slug: "toyota-camry-led-taillight-left-2012-2014",
    description: "LED-style replacement tail light with clear lens.",
    sku: "TL-CAM-12-14-L",
    category: "TAILLIGHT",
    priceCents: 13999,
    stock: 15,
    make: "Toyota",
    model: "Camry",
    yearFrom: 2012,
    yearTo: 2014,
    color: "Clear",
    side: "Left",
  },
  {
    name: "Toyota Camry LED Tail Light - Right",
    slug: "toyota-camry-led-taillight-right-2012-2014",
    description: "LED-style replacement tail light with clear lens.",
    sku: "TL-CAM-12-14-R",
    category: "TAILLIGHT",
    priceCents: 13999,
    stock: 14,
    make: "Toyota",
    model: "Camry",
    yearFrom: 2012,
    yearTo: 2014,
    color: "Clear",
    side: "Right",
  },
  {
    name: "Mercedes W204 Clear Tail Light - Left",
    slug: "mercedes-w204-clear-taillight-left-2008-2011",
    description: "OEM-style clear tail light for Mercedes-Benz C-Class W204.",
    sku: "TL-W204-08-11-L",
    category: "TAILLIGHT",
    priceCents: 15999,
    stock: 6,
    make: "Mercedes-Benz",
    model: "C-Class W204",
    yearFrom: 2008,
    yearTo: 2011,
    color: "Clear",
    side: "Left",
  },
  {
    name: "Mercedes W204 Clear Tail Light - Right",
    slug: "mercedes-w204-clear-taillight-right-2008-2011",
    description: "OEM-style clear tail light for Mercedes-Benz C-Class W204.",
    sku: "TL-W204-08-11-R",
    category: "TAILLIGHT",
    priceCents: 15999,
    stock: 5,
    make: "Mercedes-Benz",
    model: "C-Class W204",
    yearFrom: 2008,
    yearTo: 2011,
    color: "Clear",
    side: "Right",
  },
  {
    name: "Volkswagen Golf MK6 LED Tail Light - Left",
    slug: "volkswagen-golf-mk6-led-taillight-left-2009-2012",
    description:
      "LED-style clear tail light replacement for Volkswagen Golf MK6.",
    sku: "TL-GOLF6-09-12-L",
    category: "TAILLIGHT",
    priceCents: 12999,
    stock: 11,
    make: "Volkswagen",
    model: "Golf MK6",
    yearFrom: 2009,
    yearTo: 2012,
    color: "Clear",
    side: "Left",
  },

  // ---------- HEADLIGHT ----------
  {
    name: "BMW E90 Xenon Headlight - Left",
    slug: "bmw-e90-xenon-headlight-left-2005-2008",
    description: "Bi-xenon style headlight assembly, driver side.",
    sku: "HL-E90-05-08-L",
    category: "HEADLIGHT",
    priceCents: 45900,
    stock: 4,
    make: "BMW",
    model: "3 Series E90",
    yearFrom: 2005,
    yearTo: 2008,
    color: "Clear",
    side: "Left",
  },
  {
    name: "BMW E90 Xenon Headlight - Right",
    slug: "bmw-e90-xenon-headlight-right-2005-2008",
    description: "Bi-xenon style headlight assembly, passenger side.",
    sku: "HL-E90-05-08-R",
    category: "HEADLIGHT",
    priceCents: 45900,
    stock: 3,
    make: "BMW",
    model: "3 Series E90",
    yearFrom: 2005,
    yearTo: 2008,
    color: "Clear",
    side: "Right",
  },
  {
    name: "Honda Civic Projector Headlight - Left",
    slug: "honda-civic-projector-headlight-left-2006-2008",
    description: "Projector headlight with clear lens, driver side.",
    sku: "HL-CIV-06-08-L",
    category: "HEADLIGHT",
    priceCents: 18999,
    stock: 9,
    make: "Honda",
    model: "Civic",
    yearFrom: 2006,
    yearTo: 2008,
    color: "Clear",
    side: "Left",
  },
  {
    name: "Toyota Camry Headlight - Right",
    slug: "toyota-camry-headlight-right-2012-2014",
    description: "Replacement headlight assembly, passenger side.",
    sku: "HL-CAM-12-14-R",
    category: "HEADLIGHT",
    priceCents: 21999,
    stock: 0,
    make: "Toyota",
    model: "Camry",
    yearFrom: 2012,
    yearTo: 2014,
    color: "Clear",
    side: "Right",
  },

  // ---------- SIDE_MARKER ----------
  {
    name: "BMW E46 Side Marker - Amber",
    slug: "bmw-e46-side-marker-amber-1999-2005",
    description: "Amber side marker lens, sold as a pair.",
    sku: "SM-E46-99-05-AMB",
    category: "SIDE_MARKER",
    priceCents: 1999,
    stock: 40,
    make: "BMW",
    model: "3 Series E46",
    yearFrom: 1999,
    yearTo: 2005,
    color: "Amber",
    side: "Pair",
  },
  {
    name: "BMW E46 Side Marker - Smoked",
    slug: "bmw-e46-side-marker-smoked-1999-2005",
    description: "Smoked side marker lens, sold as a pair.",
    sku: "SM-E46-99-05-SMK",
    category: "SIDE_MARKER",
    priceCents: 2299,
    stock: 35,
    make: "BMW",
    model: "3 Series E46",
    yearFrom: 1999,
    yearTo: 2005,
    color: "Smoked",
    side: "Pair",
  },
  {
    name: "Mercedes W204 Side Marker - Clear",
    slug: "mercedes-w204-side-marker-clear-2008-2014",
    description: "Clear side marker lens, sold as a pair.",
    sku: "SM-W204-08-14-CLR",
    category: "SIDE_MARKER",
    priceCents: 2499,
    stock: 25,
    make: "Mercedes-Benz",
    model: "C-Class W204",
    yearFrom: 2008,
    yearTo: 2014,
    color: "Clear",
    side: "Pair",
  },

  // ---------- STOP_LIGHT ----------
  {
    name: "Honda Civic Third Brake Light",
    slug: "honda-civic-third-brake-light-2006-2011",
    description: "High-mount third brake light, red lens.",
    sku: "SL-CIV-06-11",
    category: "STOP_LIGHT",
    priceCents: 4999,
    stock: 18,
    make: "Honda",
    model: "Civic",
    yearFrom: 2006,
    yearTo: 2011,
    color: "Red",
    side: "Center",
  },
  {
    name: "Toyota Camry Third Brake Light",
    slug: "toyota-camry-third-brake-light-2012-2014",
    description: "High-mount LED brake light, smoked lens.",
    sku: "SL-CAM-12-14",
    category: "STOP_LIGHT",
    priceCents: 5999,
    stock: 12,
    make: "Toyota",
    model: "Camry",
    yearFrom: 2012,
    yearTo: 2014,
    color: "Smoked",
    side: "Center",
  },

  // ---------- FOG_LIGHT ----------
  {
    name: "BMW E90 Fog Light - Left",
    slug: "bmw-e90-fog-light-left-2005-2008",
    description: "Front bumper fog light, clear lens, driver side.",
    sku: "FL-E90-05-08-L",
    category: "FOG_LIGHT",
    priceCents: 6999,
    stock: 10,
    make: "BMW",
    model: "3 Series E90",
    yearFrom: 2005,
    yearTo: 2008,
    color: "Clear",
    side: "Left",
  },
  {
    name: "BMW E90 Fog Light - Right",
    slug: "bmw-e90-fog-light-right-2005-2008",
    description: "Front bumper fog light, clear lens, passenger side.",
    sku: "FL-E90-05-08-R",
    category: "FOG_LIGHT",
    priceCents: 6999,
    stock: 9,
    make: "BMW",
    model: "3 Series E90",
    yearFrom: 2005,
    yearTo: 2008,
    color: "Clear",
    side: "Right",
  },
] as const;

async function main() {
  // Start clean so the script can be run many times (also removes test products)
  await prisma.product.deleteMany();

  await prisma.product.createMany({
    data: products.map((product) => ({ ...product })),
  });

  console.log(`Seeded ${products.length} products`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
