import { PrismaClient } from "../src/generated/prisma/client.js";

const prisma = new PrismaClient();

async function main() {
  const products = await prisma.product.createMany({
    data: [
      {
        name: "Honda Civic Clear Tail Light - Left",
        slug: "honda-civic-clear-taillight-left-2006-2008",
        description: "OEM-style clear lens tail light, driver side.",
        sku: "TL-CIV-06-08-L",
        category: "TAILLIGHT",
        priceCents: 8999,
        stock: 12,
        make: "Honda",
        model: "Civic",
        yearFrom: 2006,
        yearTo: 2008,
        color: "Clear",
        side: "Left",
      },
      {
        name: "Honda Civic Clear Tail Light - Right",
        slug: "honda-civic-clear-taillight-right-2006-2008",
        description: "OEM-style clear lens tail light, passenger side.",
        sku: "TL-CIV-06-08-R",
        category: "TAILLIGHT",
        priceCents: 8999,
        stock: 10,
        make: "Honda",
        model: "Civic",
        yearFrom: 2006,
        yearTo: 2008,
        color: "Clear",
        side: "Right",
      },
      {
        name: "BMW E46 Clear Tail Light - Left",
        slug: "bmw-e46-clear-taillight-left-1999-2001",
        description: "Clear lens tail light replacement for BMW E46.",
        sku: "TL-E46-99-01-L",
        category: "TAILLIGHT",
        priceCents: 11999,
        stock: 8,
        make: "BMW",
        model: "3 Series E46",
        yearFrom: 1999,
        yearTo: 2001,
        color: "Clear",
        side: "Left",
      },
      {
        name: "BMW E46 Clear Tail Light - Right",
        slug: "bmw-e46-clear-taillight-right-1999-2001",
        description: "Clear lens tail light replacement for BMW E46.",
        sku: "TL-E46-99-01-R",
        category: "TAILLIGHT",
        priceCents: 11999,
        stock: 7,
        make: "BMW",
        model: "3 Series E46",
        yearFrom: 1999,
        yearTo: 2001,
        color: "Clear",
        side: "Right",
      },
      {
        name: "Toyota Camry LED Tail Light - Left",
        slug: "toyota-camry-led-taillight-left-2012-2014",
        description: "LED-style replacement tail light with clear lens.",
        sku: "TL-CAM-12-14-L",
        category: "TAILLIGHT",
        priceCents: 13999,
        stock: 15,
        make: "Toyota",
        model: "Camry",
        yearFrom: 2012,
        yearTo: 2014,
        color: "Clear",
        side: "Left",
      },
      {
        name: "Toyota Camry LED Tail Light - Right",
        slug: "toyota-camry-led-taillight-right-2012-2014",
        description: "LED-style replacement tail light with clear lens.",
        sku: "TL-CAM-12-14-R",
        category: "TAILLIGHT",
        priceCents: 13999,
        stock: 14,
        make: "Toyota",
        model: "Camry",
        yearFrom: 2012,
        yearTo: 2014,
        color: "Clear",
        side: "Right",
      },
      {
        name: "Mercedes W204 Clear Tail Light - Left",
        slug: "mercedes-w204-clear-taillight-left-2008-2011",
        description:
          "OEM-style clear tail light for Mercedes-Benz C-Class W204.",
        sku: "TL-W204-08-11-L",
        category: "TAILLIGHT",
        priceCents: 15999,
        stock: 6,
        make: "Mercedes-Benz",
        model: "C-Class W204",
        yearFrom: 2008,
        yearTo: 2011,
        color: "Clear",
        side: "Left",
      },
      {
        name: "Mercedes W204 Clear Tail Light - Right",
        slug: "mercedes-w204-clear-taillight-right-2008-2011",
        description:
          "OEM-style clear tail light for Mercedes-Benz C-Class W204.",
        sku: "TL-W204-08-11-R",
        category: "TAILLIGHT",
        priceCents: 15999,
        stock: 5,
        make: "Mercedes-Benz",
        model: "C-Class W204",
        yearFrom: 2008,
        yearTo: 2011,
        color: "Clear",
        side: "Right",
      },
      {
        name: "Volkswagen Golf MK6 LED Tail Light - Left",
        slug: "volkswagen-golf-mk6-led-taillight-left-2009-2012",
        description:
          "LED-style clear tail light replacement for Volkswagen Golf MK6.",
        sku: "TL-GOLF6-09-12-L",
        category: "TAILLIGHT",
        priceCents: 12999,
        stock: 11,
        make: "Volkswagen",
        model: "Golf MK6",
        yearFrom: 2009,
        yearTo: 2012,
        color: "Clear",
        side: "Left",
      },
      {
        name: "Volkswagen Golf MK6 LED Tail Light - Right",
        slug: "volkswagen-golf-mk6-led-taillight-right-2009-2012",
        description:
          "LED-style clear tail light replacement for Volkswagen Golf MK6.",
        sku: "TL-GOLF6-09-12-R",
        category: "TAILLIGHT",
        priceCents: 12999,
        stock: 9,
        make: "Volkswagen",
        model: "Golf MK6",
        yearFrom: 2009,
        yearTo: 2012,
        color: "Clear",
        side: "Right",
      },
    ],
  });

  console.log(`Created ${products.count} products`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
